name: creationhub-adminer

services:
  adminer:
    image: adminer
    container_name: creationhub-adminer
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=system
    networks:
      - backend
      - egress
    ports:
      - "8083:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula

networks:
  backend:
    external: true
    name: creationhub-backend
  egress:
    external: true
    name: creationhub-egress

