services:
  ollama:
    image: ollama/ollama:latest
    container_name: creationhub_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ${AI_DATA_PATH:-./volumes/ai_models}:/root/.ollama
    networks:
      - creationhub-backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  creationhub-backend:
    external: true
