name: creationhub-ai-translate

services:
  # LibreTranslate (Offline Translation API)
  # Docs: https://github.com/LibreTranslate/LibreTranslate
  ai-translate:
    image: libretranslate/libretranslate:latest
    container_name: creationhub-ai-translate
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=apps
    networks:
      - backend
      - egress
    ports:
      - "5000:5000" # Internal API
    volumes:
      - /home/inno/creationhub/orchestration/volumes/ai/translate:/app/db
    environment:
      - LT_HOST=0.0.0.0
      - LT_PORT=5000
      - LT_UPDATE_MODELS=true
      # Only load these languages (en=English, de=German, ru=Russian, hi=Hindi, pt=Portuguese-Brazilian)
      - LT_LOAD_ONLY=en,de,ru,hi,pt

networks:
  backend:
    external: true
    name: creationhub-backend
  egress:
    external: true
    name: creationhub-egress
