name: creationhub

networks:
  backend:
    name: creationhub-backend
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 100.64.10.0/24
  
  egress:
    name: creationhub-egress
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 100.64.20.0/24
