name: creationhub-homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: creationhub-homepage
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=apps
    networks:
      - backend
      - egress
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - HOMEPAGE_ALLOWED_HOSTS=*
    volumes:
      - /home/inno/creationhub/orchestration/volumes/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /:/mnt/host:ro # Access specifically for Disk Widget

networks:
  backend:
    external: true
    name: creationhub-backend
  egress:
    external: true
    name: creationhub-egress

