name: creationhub-n8n

services:
  n8n:
    build:
      context: ../builds/n8n-python
      dockerfile: Dockerfile
    image: creationhub-n8n-python:latest
    container_name: creationhub-n8n
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=n8n
    networks:
      - backend
      - egress
    ports:
      - "5678:5678" # Only strictly required if not using NPM, but useful for LAN access
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=db_n8n
      - DB_POSTGRESDB_USER=user_n8n
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD} # In prod, should use specific user password
      
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${ADMIN_EMAIL}
      - N8N_BASIC_AUTH_PASSWORD=${POSTGRES_PASSWORD} # Temporary mapping
      
      - N8N_HOST=${CREATIONHUB_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false # Critical for LAN IP access
      
      - WEBHOOK_URL=http://${CREATIONHUB_HOST}:5678/
      
    volumes:
      - /home/inno/creationhub/orchestration/volumes/n8n:/home/node/.n8n
      # Shared media volume for processing
      - /home/inno/creationhub/orchestration/volumes/media:/media_root
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

# Networks defined in base.yml
