name: creationhub-redis

services:
  redis:
    image: redis:7-alpine
    container_name: creationhub-redis
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=system
    networks:
      - backend
    volumes:
      - /home/inno/creationhub/orchestration/volumes/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

