name: creationhub-rsshub

services:
  rsshub:
    image: diygod/rsshub:latest
    container_name: creationhub-rsshub
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=apps
    networks:
      - backend
      - egress
    ports:
      - "1200:1200"
    environment:
      - CACHE_TYPE=redis
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/
    depends_on:
      - redis

