#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# CreationHub Configuration Applicator (apply_config.sh)
# Logic: Reads state/answers.json -> Applies System Changes -> Generates .env
# ==============================================================================

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
STATE_DIR="$PROJECT_ROOT/state"
ANSWERS_FILE="$STATE_DIR/answers.json"
ENV_FILE="$PROJECT_ROOT/.env"

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
log_info() { echo "[CONFIG] $1"; }
log_warn() { echo "[CONFIG] WARNING: $1" >&2; }
log_err()  { echo "[CONFIG] ERROR: $1" >&2; }

require_root() {
    if [[ $EUID -ne 0 ]]; then
        log_err "Must run as root."
        exit 1
    fi
}

load_answers() {
    if [[ ! -f "$ANSWERS_FILE" ]]; then
        log_err "State file not found: $ANSWERS_FILE"
        exit 1
    fi
    # Validate JSON syntax
    if ! jq . "$ANSWERS_FILE" >/dev/null 2>&1; then
        log_err "Invalid JSON in $ANSWERS_FILE"
        exit 1
    fi
}

get_answer() {
    jq -r ".$1 // empty" "$ANSWERS_FILE"
}

# ------------------------------------------------------------------------------
# System Configuration
# ------------------------------------------------------------------------------
apply_system_settings() {
    local target_tz
    local target_host

    target_tz=$(get_answer "timezone")
    target_host=$(get_answer "hostname")

    if [[ -n "$target_tz" ]]; then
        log_info "Setting timezone to $target_tz"
        timedatectl set-timezone "$target_tz"
    fi

    if [[ -n "$target_host" ]]; then
        current_host=$(hostname)
        if [[ "$current_host" != "$target_host" ]]; then
            log_info "Setting hostname to $target_host"
            hostnamectl set-hostname "$target_host"
            # Update /etc/hosts to prevent sudo warnings
            sed -i "s/127.0.0.1  localhost/127.0.0.1  localhost $target_host/g" /etc/hosts || true
        fi
    fi
}

# ------------------------------------------------------------------------------
# Network / WireGuard / DNS
# ------------------------------------------------------------------------------
apply_networking() {
    local wg_enabled
    local dns_provider
    
    wg_enabled=$(get_answer "wireguard_enabled")
    dns_provider=$(get_answer "dns_provider")

    # Ensure systemd-resolved is active
    if ! systemctl is-active --quiet systemd-resolved; then
        log_info "Enabling systemd-resolved..."
        systemctl enable --now systemd-resolved
    fi

    if [[ "$wg_enabled" == "true" ]]; then
        log_info "WireGuard is ENABLED. Enforcing VPN DNS."
        # In a real scenario, we would configure /etc/wireguard/wg0.conf here
        # For now, we ensure the tool is installed and module loaded
        modprobe wireguard || true
    else
        log_info "WireGuard is DISABLED. Enforcing DNS: $dns_provider"
        # Force global DNS settings
        # Note: This overrides typical DHCP DNS properly on Ubuntu Systemd systems
        mkdir -p /etc/systemd/resolved.conf.d
        cat > /etc/systemd/resolved.conf.d/creationhub.conf <<EOF
[Resolve]
DNS=$dns_provider
FallbackDNS=1.1.1.1 8.8.8.8
DNSStubListener=yes
EOF
        systemctl restart systemd-resolved
    fi
}

# ------------------------------------------------------------------------------
# Environment Generation (.env)
# ------------------------------------------------------------------------------
generate_env() {
    log_info "Generating .env file..."
    
    # Touch file and restrict immediately
    touch "$ENV_FILE"
    chmod 600 "$ENV_FILE"

    {
        echo "# GENERATED BY apply_config.sh - DO NOT EDIT MANUALLY"
        echo "# TIMESTAMP: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        echo ""
        
        echo "# --- System Identity ---"
        echo "CREATIONHUB_HOST=$(get_answer "hostname")"
        echo "ADMIN_EMAIL=$(get_answer "admin_email")"
        echo "TZ=$(get_answer "timezone")"
        
        echo ""
        echo "# --- Secrets ---"
        echo "POSTGRES_PASSWORD=$(get_answer "db_password")"
        echo "REDIS_PASSWORD=$(get_answer "db_password")" # Simplified for V1
        
        echo ""
        echo "# --- Network ---"
        echo "WIREGUARD_ENABLED=$(get_answer "wireguard_enabled")"
        echo "LAN_IP=$(get_answer "lan_ip")"
        
        echo ""
        echo "# --- AI Storage ---"
        echo "AI_DATA_PATH=$(get_answer "ai_storage_path")"

        
        # Parse enabled services and add their configs if needed
        RAW=$(get_answer "services_raw" | tr -d '"')
        echo ""
        echo "# --- Enabled Services: $RAW ---"
        
        # Here we could generate per-service secrets if we had a rotation system.
        # For V1 "Master Spec", we use the global password for simplicity or reuse it
        # unless specifically asked to generate random ones.
        # Spec says: "re-run must not 'randomly' change passwords". 
        # So we reuse the main password or generate stable ones if we had a vault.
        # We will map them to standard Env Vars.
        
        
    } > "$ENV_FILE"

    log_info ".env generated with permissions 600."
}

# ------------------------------------------------------------------------------
# Dynamic Dashboard Generator
# ------------------------------------------------------------------------------
generate_dashboard_config() {
    log_info "Generating Dynamic Dashboard Configuration..."
    
    local dash_dir="$PROJECT_ROOT/volumes/homepage/config"
    mkdir -p "$dash_dir"
    
    # 1. settings.yaml with TABS
    cat > "$dash_dir/settings.yaml" <<EOF
title: CreationHub
background:
  image: "" 
  color: "#111217"
theme: dark
color: slate
layout:
  Work:
    tab: Work
    style: row
    columns: 3
  Data:
    tab: Data
    style: row
    columns: 3
  Admin:
    tab: Admin
    style: row
    columns: 4
EOF

    # 1b. docker.yaml (Enable Status Dots)
    cat > "$dash_dir/docker.yaml" <<EOF
my-docker:
  socket: /var/run/docker.sock
EOF

    # 1b. docker.yaml (Enable Status Dots) - FIXED
    cat > "$dash_dir/docker.yaml" <<EOF
my-docker:
  socket: /var/run/docker.sock
EOF

    # 2. custom.css (Strict Enterprise Theme)
    cat > "$dash_dir/custom.css" <<EOF
/* Font Import */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');

:root {
    --bg-color: #0f172a;
    --card-bg: #1e293b;
    --text-primary: #f1f5f9;
    --text-secondary: #94a3b8;
    --border-color: #334155;
    --accent-color: #3b82f6;
    --success-color: #22c55e;
    --danger-color: #ef4444;
}

body {
    background: var(--bg-color) !important;
    font-family: 'Inter', sans-serif !important;
    color: var(--text-primary) !important;
}

/* CARDS: Solid, No Blur, No Glass */
.services .service {
    background: var(--card-bg) !important;
    border: 1px solid var(--border-color) !important;
    border-radius: 8px !important;
    backdrop-filter: none !important;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1) !important;
}

.services .service:hover {
    border-color: var(--accent-color) !important;
    transform: translateY(-2px);
}

/* HEADERS & TEXT */
.service-name {
    color: var(--text-primary) !important;
    font-weight: 600 !important;
}
.service-desc {
    color: var(--text-secondary) !important;
}

/* PROGRESS BARS: Clean, Single Color */
.progress-bar-fill {
    background: var(--accent-color) !important;
}
.progress-track {
    background: #334155 !important;
}

/* SEARCH BAR */
.search-bar {
    background: var(--card-bg) !important;
    border: 1px solid var(--border-color) !important;
    border-radius: 6px !important;
}
EOF

    # 3. widgets.yaml (Super Dashboard Stats)
    cat > "$dash_dir/widgets.yaml" <<EOF
- search:
    provider: google
    target: _blank
    focus: true

- resources:
    cpu: true
    memory: true
    disk: /mnt/host
    label: System

- resources:
    disk: /app/config
    label: Configs

- glances:
    url: http://creationhub-glances:61208
    label: Monitor
    metric: cpu

- customapi:
    url: http://creationhub-vpn-manager:5000/api/status
    refreshInterval: 30000
    mappings:
      - field: city
        label: City
      - field: country
        label: Country  
      - field: ip
        label: IP
    
- datetime:
    text_size: xl
    format:
        timeStyle: short
        dateStyle: medium
EOF

    # 2. services.yaml
    local lan_ip
    lan_ip=$(get_answer "lan_ip")
    # If lan_ip is "auto", try to detect, or fallback to hostname for internal
    if [[ "$lan_ip" == "auto" ]] || [[ -z "$lan_ip" ]]; then
       # Try robust IP detection (primary interface)
       lan_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')
       if [[ -z "$lan_ip" ]]; then
           lan_ip=$(hostname -I | awk '{print $1}')
       fi
    fi
    log_info "Dashboard Links will use Host: http://$lan_ip"
    
    # Start building services.yaml
    echo "---" > "$dash_dir/services.yaml"
    
    local svc_list
    svc_list=$(get_answer "services_raw" | tr -d '"')
    
    # Helper to check if service enabled
    has_svc() { [[ "$svc_list" == *"$1"* ]]; }

    # ========== TAB: WORK ==========
    echo "- Work:" >> "$dash_dir/services.yaml"
    
    # Automation Core
    if has_svc "n8n"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - n8n:
        icon: n8n
        href: http://$lan_ip:5678
        description: Workflow Automation
        server: my-docker
        container: creationhub-n8n
EOF
    fi
    
    # Media
    if has_svc "media"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - yt-dlp:
        icon: youtube
        href: http://$lan_ip:8080/api/info
        description: Video Downloader
        server: my-docker
        container: creationhub-yt-dlp
EOF
    fi
    
    # Browserless
    if has_svc "browserless"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Browserless:
        icon: chrome
        href: http://$lan_ip:3002
        description: Headless Browser
        server: my-docker
        container: creationhub-browserless
EOF
    fi
    
    # RSS
    if has_svc "rsshub"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - RSSHub:
        icon: rss
        href: http://$lan_ip:1200
        description: RSS Feeds
        server: my-docker
        container: creationhub-rsshub
EOF
    fi
    
    # AI Tools
    if has_svc "ai-transcribe"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Whisper:
        icon: openai
        href: http://$lan_ip:8000/docs
        description: Speech-to-Text
        server: my-docker
        container: creationhub-ai-transcribe
EOF
    fi
    if has_svc "ai-translate"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Translate:
        icon: google-translate
        href: http://$lan_ip:5000
        description: LibreTranslate
        server: my-docker
        container: creationhub-ai-translate
EOF
    fi

    # ========== TAB: DATA ==========
    echo "- Data:" >> "$dash_dir/services.yaml"
    
    if has_svc "grafana"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Grafana:
        icon: grafana
        href: http://$lan_ip:3000
        description: Analytics & Dashboards
        server: my-docker
        container: creationhub-grafana
EOF
    fi
    if has_svc "nextcloud"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Nextcloud:
        icon: nextcloud
        href: http://$lan_ip:8081
        description: Cloud Storage
        server: my-docker
        container: creationhub-nextcloud
EOF
    fi
    if has_svc "filebrowser"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Filebrowser:
        icon: filebrowser
        href: http://$lan_ip:8082
        description: File Manager
        server: my-docker
        container: creationhub-filebrowser
EOF
    fi
    
    # Channel Manager (Direct Link, no iframe)
    cat >> "$dash_dir/services.yaml" <<EOF
    - Channels:
        icon: youtube
        href: http://$lan_ip:5002
        description: Manage Accounts
        server: my-docker
        container: creationhub-channel-manager
EOF

    # ========== TAB: ADMIN ==========
    echo "- Admin:" >> "$dash_dir/services.yaml"
    
    if has_svc "portainer"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Portainer:
        icon: portainer
        href: http://$lan_ip:9000
        description: Docker UI
        server: my-docker
        container: creationhub-portainer
EOF
    fi
    if has_svc "npm"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - NPM:
        icon: nginx-proxy-manager
        href: http://$lan_ip:81
        description: Reverse Proxy
        server: my-docker
        container: creationhub-npm
EOF
    fi
    if has_svc "dozzle"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Logs:
        icon: dozzle
        href: http://$lan_ip:8888
        description: Container Logs
        server: my-docker
        container: creationhub-dozzle
EOF
    fi
    if has_svc "glances"; then
        cat >> "$dash_dir/services.yaml" <<EOF
    - Glances:
        icon: glances
        href: http://$lan_ip:61208
        description: System Monitor
        server: my-docker
        container: creationhub-glances
        widget:
            type: glances
            url: http://$lan_ip:61208
            version: 4
            metric: cpu
EOF
    fi
    
    # Database Admin
    cat >> "$dash_dir/services.yaml" <<EOF
    - Adminer:
        icon: adminer
        href: http://$lan_ip:8083
        description: Database Admin
        server: my-docker
        container: creationhub-adminer
    - Healthchecks:
        icon: healthchecks
        href: http://$lan_ip:8001
        description: Uptime Monitor
        server: my-docker
        container: creationhub-healthchecks
EOF
    
    # VPN
    cat >> "$dash_dir/services.yaml" <<EOF
    - WireGuard:
        icon: wireguard
        href: http://$lan_ip:5003
        description: VPN Config
        server: my-docker
        container: creationhub-wireguard-ui
    - VPN Status:
        icon: tailscale
        href: http://$lan_ip:5001
        description: Connection Info
        server: my-docker
        container: creationhub-vpn-manager
EOF
    
    log_info "Dashboard configured for host: $lan_ip"
}

# ------------------------------------------------------------------------------
# Public Landing Page Generator
# ------------------------------------------------------------------------------
generate_landing_page() {
    log_info "Generating Public Portal..."
    
    local landing_dir="$PROJECT_ROOT/volumes/landing"
    mkdir -p "$landing_dir"
    
    local telegram=$(get_answer "telegram_contact")
    local email="contact@innoguru.ru"

    cat > "$landing_dir/index.html" <<EOF
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>InnoGuru | AI & Tech</title>
    <style>
        :root { --bg: #0f172a; --card: #1e293b; --accent: #8b5cf6; --text: #e2e8f0; }
        body { margin: 0; font-family: 'Courier New', monospace; background: var(--bg); color: var(--text); overflow-x: hidden; }
        .container { max-width: 800px; margin: 0 auto; padding: 2rem; }
        
        #matrix { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: -1; opacity: 0.1; }
        
        header { text-align: center; margin-bottom: 3rem; border-bottom: 1px solid var(--accent); padding-bottom: 1rem; position: relative; }
        h1 { font-size: 2.5rem; text-transform: uppercase; letter-spacing: 4px; color: var(--accent); text-shadow: 0 0 10px var(--accent); margin-bottom: 0.5rem; }
        
        .lang-switch { position: absolute; top: 0; right: 0; cursor: pointer; border: 1px solid var(--accent); padding: 5px 10px; font-size: 0.8rem; color: var(--accent); border-radius: 4px; }
        .lang-switch:hover { background: var(--accent); color: #fff; }

        .grid { display: grid; grid-template-columns: 1fr; gap: 2rem; }
        @media(min-width: 600px) { .grid { grid-template-columns: 1fr 1fr; } }
        
        .card { background: var(--card); padding: 1.5rem; border-radius: 8px; border: 1px solid #334155; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
        .card h2 { margin-top: 0; color: #60a5fa; border-bottom: 1px dashed #475569; padding-bottom: 0.5rem; font-size: 1.2rem; }
        
        .crypto-item { display: flex; justify-content: space-between; margin-bottom: 0.5rem; border-bottom: 1px solid #334155; padding-bottom: 0.2rem; }
        .val { font-weight: bold; color: #34d399; }
        .fear-val { color: #fbbf24; }
        
        .rss-item { font-size: 0.9rem; margin-bottom: 1rem; }
        .rss-item a { color: var(--text); text-decoration: none; transition: color 0.2s; }
        .rss-item a:hover { color: var(--accent); }
        .date { font-size: 0.7rem; color: #64748b; display: block; margin-top: 0.2rem; }
        
        footer { text-align: center; margin-top: 4rem; font-size: 0.8rem; color: #64748b; }
        .btn { display: inline-block; padding: 0.5rem 1rem; background: var(--accent); color: white; text-decoration: none; border-radius: 4px; margin: 0 0.5rem; transition: all 0.2s; }
        .btn:hover { background: #7c3aed; transform: translateY(-2px); }
    </style>
</head>
<body>
    <canvas id="matrix"></canvas>
    
    <div class="container">
        <header>
            <div class="lang-switch" onclick="toggleLang()">RU / EN</div>
            <h1>InnoGuru</h1>
            <p id="subtitle">Искусственный Интеллект • Крипто • Технологии</p>
        </header>

        <div class="grid">
            <div class="card">
                <h2 id="lbl-market">РЫНОК</h2>
                <div id="crypto-loading">Загрузка данных...</div>
                <div id="crypto-data" style="display:none;">
                    <div class="crypto-item">
                        <span>BTC/USD</span>
                        <span class="val" id="btc-price">---</span>
                    </div>
                    <div class="crypto-item">
                        <span>ETH/USD</span>
                        <span class="val" id="eth-price">---</span>
                    </div>
                    <div class="crypto-item" style="margin-top: 1rem;">
                        <span id="lbl-fear">Индекс Страха</span>
                        <span class="fear-val" id="fear-index">---</span>
                    </div>
                </div>
            </div>

            <div class="card">
                <h2 id="lbl-contact">КОНТАКТЫ</h2>
                <p><span id="lbl-status">Статус</span>: <span style="color:#34d399">ONLINE</span></p>
                <div style="text-align: center; margin-top: 2rem;">
                    <a href="mailto:$email" class="btn">EMAIL</a>
                    <a href="https://t.me/$telegram" class="btn">TELEGRAM</a>
                </div>
            </div>
        </div>

        <div class="card" style="margin-top: 2rem;">
            <h2 id="lbl-news">НОВОСТИ AI</h2>
            <div id="rss-feed">scanning...</div>
        </div>

        <footer>
            <p>System ID: DO-01 | Powered by CreationHub v1.12</p>
        </footer>
    </div>

    <script>
        const DICT = {
            ru: {
                subtitle: "Искусственный Интеллект • Крипто • Технологии",
                market: "РЫНОК",
                contact: "КОНТАКТЫ",
                status: "Статус",
                news: "НОВОСТИ AI",
                fear: "Индекс Страха",
                loading: "Загрузка данных...",
                rss_url: 'https://habr.com/ru/rss/hubs/artificial_intelligence/articles/'
            },
            en: {
                subtitle: "Artificial Intelligence • Crypto • Technologies",
                market: "MARKET DATA",
                contact: "CONTACT UPLINK",
                status: "Status",
                news: "AI NEWS FEED",
                fear: "Fear Index",
                loading: "Connecting to blockchain...",
                rss_url: 'https://www.wired.com/feed/tag/ai/latest/rss'
            }
        };

        let currentLang = 'ru';

        function toggleLang() {
            currentLang = currentLang === 'ru' ? 'en' : 'ru';
            applyLang();
            fetchRSS(); // Refresh news source
        }

        function applyLang() {
            const d = DICT[currentLang];
            document.getElementById('subtitle').innerText = d.subtitle;
            document.getElementById('lbl-market').innerText = d.market;
            document.getElementById('lbl-contact').innerText = d.contact;
            document.getElementById('lbl-status').innerText = d.status;
            document.getElementById('lbl-news').innerText = d.news;
            document.getElementById('lbl-fear').innerText = d.fear;
            document.getElementById('crypto-loading').innerText = d.loading;
        }

        // --- CORE FUNCTIONS (Same logic, updated for dynamic lang) ---

        const canvas = document.getElementById('matrix');
        const ctx = canvas.getContext('2d');
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        const letters = "0101010101 INNOGURU AI CRYPTO TECH ";
        const fontSize = 14;
        const columns = canvas.width / fontSize;
        const drops = Array(Math.floor(columns)).fill(1);
        function draw() {
            ctx.fillStyle = 'rgba(15, 23, 42, 0.05)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.fillStyle = '#0f0';
            ctx.font = fontSize + 'px monospace';
            for(let i=0; i<drops.length; i++) {
                const text = letters.charAt(Math.floor(Math.random()*letters.length));
                ctx.fillText(text, i*fontSize, drops[i]*fontSize);
                if(drops[i]*fontSize > canvas.height && Math.random() > 0.975) drops[i] = 0;
                drops[i]++;
            }
        }
        setInterval(draw, 50);

        async function fetchCrypto() {
            try {
                const response = await fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd');
                const data = await response.json();
                document.getElementById('btc-price').textContent = '$' + data.bitcoin.usd.toLocaleString();
                document.getElementById('eth-price').textContent = '$' + data.ethereum.usd.toLocaleString();
                
                const fearResp = await fetch('https://api.alternative.me/fng/');
                const fearData = await fearResp.json();
                document.getElementById('fear-index').textContent = fearData.data[0].value;
                document.getElementById('crypto-loading').style.display = 'none';
                document.getElementById('crypto-data').style.display = 'block';
            } catch(e) { console.error(e); }
        }
        fetchCrypto();

        async function fetchRSS() {
            document.getElementById('rss-feed').innerHTML = '<div style="color:#64748b">...</div>';
            const RSS_URL = DICT[currentLang].rss_url;
            try {
                const res = await fetch('https://api.rss2json.com/v1/api.json?rss_url=' + encodeURIComponent(RSS_URL));
                const data = await res.json();
                let html = '';
                // Habr feed cleaning
                data.items.slice(0, 3).forEach(item => {
                    html += \`<div class="rss-item">
                        <a href="\${item.link}" target="_blank">► \${item.title}</a>
                        <span class="date">\${item.pubDate}</span>
                    </div>\`;
                });
                document.getElementById('rss-feed').innerHTML = html;
            } catch(e) {
                 document.getElementById('rss-feed').textContent = "Feed unavailable";
            }
        }
        fetchRSS();
    </script>
</body>
</html>
EOF
}

# ------------------------------------------------------------------------------
# Database Initialization Script
# ------------------------------------------------------------------------------
generate_db_init() {
    log_info "Generating PostgreSQL init script..."
    local db_pass
    db_pass=$(get_answer "db_password")
    local init_dir="$PROJECT_ROOT/volumes/postgres-init"
    
    mkdir -p "$init_dir"
    
    cat > "$init_dir/init.sql" <<EOF
-- GENERATED BY apply_config.sh
-- CreationHub Database Initialization

-- n8n
CREATE USER user_n8n WITH PASSWORD '$db_pass';
CREATE DATABASE db_n8n WITH OWNER user_n8n;
GRANT ALL PRIVILEGES ON DATABASE db_n8n TO user_n8n;

-- Nextcloud
CREATE USER user_nextcloud WITH PASSWORD '$db_pass';
CREATE DATABASE db_nextcloud WITH OWNER user_nextcloud;
GRANT ALL PRIVILEGES ON DATABASE db_nextcloud TO user_nextcloud;

-- Healthchecks
CREATE USER user_healthchecks WITH PASSWORD '$db_pass';
CREATE DATABASE db_healthchecks WITH OWNER user_healthchecks;
GRANT ALL PRIVILEGES ON DATABASE db_healthchecks TO user_healthchecks;

-- Analytics (Grafana/n8n)
CREATE USER user_analytics WITH PASSWORD '$db_pass';
CREATE DATABASE db_analytics WITH OWNER user_analytics;
GRANT ALL PRIVILEGES ON DATABASE db_analytics TO user_analytics;
EOF
    log_info "init.sql created."
}

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------
main() {
    require_root
    load_answers
    
    log_info "Starting configuration application..."
    
    apply_system_settings
    apply_networking
    generate_env
    generate_db_init
    generate_dashboard_config
    generate_landing_page
    
    # Filebrowser DB Fix (Prevent directory creation)
    mkdir -p "$PROJECT_ROOT/volumes/filebrowser"
    touch "$PROJECT_ROOT/volumes/filebrowser/filebrowser.db"

    # 5. Fix Permissions (Crucial step)
    log_info "Enforcing permissions..."
    
    # General Rule: 1000:1000 for most services
    # We exclude specific special directories first to avoid stomping them
    find "$PROJECT_ROOT/volumes" -maxdepth 1 -mindepth 1 \
        -not -name "postgres" \
        -not -name "grafana" \
        -not -name "nextcloud" \
        -not -name "wireguard-ui" \
        -exec chown -R 1000:1000 {} \;        -not -name "postgres" \
        -not -name "grafana" \
        -not -name "nextcloud" \
        -exec chown -R 1000:1000 {} \;
    
    # Special Cases:
    
    # Nextcloud (UID 33)
    if [[ -d "$PROJECT_ROOT/volumes/nextcloud" ]]; then
       log_info "Fixing Nextcloud permissions (www-data:www-data)..."
       chown -R 33:33 "$PROJECT_ROOT/volumes/nextcloud"
    fi

    # Grafana (UID 472)
    if [[ -d "$PROJECT_ROOT/volumes/grafana" ]]; then
       log_info "Fixing Grafana permissions (472:472)..."
       chown -R 472:472 "$PROJECT_ROOT/volumes/grafana"
    fi
    
    # Postgres (UID 999 or 70 depending on alpine/debian)
    # We skip chowning it to allow container self-management, or set to 70 (alpine result)
    # For stability, if it works now, we leave it alone (excluded above).
    
    chown 1000:1000 "$ENV_FILE"
    
    log_info "Configuration applied successfully."
}

main "$@"
